name: Build and Deploy GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, devlin10]
    steps:
      - uses: actions/checkout@v4
      - name: Test Runner
        run: echo "Hello from self-hosted runner!"
